services:
  bloodhound_gang:
    build: .
    image: kbaybekov/bloodhound_gang:latest
    container_name: bloodhound_gang
    restart: unless-stopped
    user: "${UID:-1000}:${GID:-1000}"
    env_file:
      - .env                      # переменные из внешнего .env попадут в окружение контейнера
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      # SSH-ключи (read-only)
      - ${HOME}/.ssh:/home/bloodhound_gang/.ssh:ro

      # Внешний .env монтируется как файл, чтобы dotenv мог его прочитать при старте
      - ./.env:/home/bloodhound_gang/.env:ro

      # Внешняя папка conf/ затеняет встроенную /home/bloodhound_gang/conf/
      - ./conf:/home/bloodhound_gang/conf:ro

      # Внешняя папка data/logs/ затеняет встроенную /home/bloodhound_gang/conf/
      - ./data/logs/:/home/bloodhound_gang/logs:rw

      # Если существует внешняя папка tasks/, она затеняет src/tasks/
      # Используем bind mount с опциональным созданием (если папки нет, Docker создаст пустую)
      - ./tasks:/home/bloodhound_gang/src/tasks:ro

      # Рабочие директории (пути берутся из .env, должны существовать на хосте)
      - ${SRC_D}:${SRC_D}:ro
      - ${RES_D}:${RES_D}:rw
      - ${WORK_D}:${WORK_D}:rw
      - ${LOG_D}:${LOG_D}:rw

      # Данные (сохраняются на хосте)
      - ./data/:/home/bloodhound_gang/data/:rw

    ports:
      - "${HTTP_METRICS_PORT:-8000}:${HTTP_METRICS_PORT:-8000}"
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:v3.12.0
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./data/prometheus/:/prometheus:rw
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:12.4.2
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_AUTH_BASIC_ENABLED=false
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_PLUGINS_PREINSTALL=grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./data/grafana/:/var/lib/grafana
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml:ro
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    networks:
      - monitoring
    depends_on:
      - prometheus

networks:
  monitoring:
    driver: bridge
